---
- name: basic installation - Install vim and curl. Format volumn and mount it.
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: apt
    copy:
        src: ../au_archive_ubuntu_com_ubuntu.list
        dest: /etc/apt/sources.list.d/au_archive_ubuntu_com_ubuntu.list
  - name: apt-get update
    apt: update_cache=yes

  - name: Install vim and curl
    apt: name={{item}}
    with_items:
        - vim
        - curl
  
  - name: Create the directory
    file:
      path: /extra
      state: directory

  - name: Mount
    command: "{{ item }}"
    with_items:
      - touch 123

  - name: Change the permission of the mount directory
    file:
      path: /extra
      state: directory
      mode: 0777
      owner: ubuntu



#  - name: Change the password
#    shell: "{{item}}"
#    with_items:
#      - echo -e "cqmygysdss\ncqmygysdss" | sudo passwd ubuntu